@startuml
skinparam wrapWidth 300
skinparam maxMessageSize 300
skinparam ArrowThickness 2
skinparam DefaultFontStyle bold
skinparam DefaultFontName Arial
skinparam DefaultFontSize 24

actor USER
participant "Agent / Orchestrator" as AGENT
participant "Function Tools" as FUNCTIONS
participant "LLM" as LLM

== Tool Catalog Gathering ==
AGENT -> FUNCTIONS : Fetch Tool Catalog
AGENT <- FUNCTIONS : Return Catalog\n(product_info, store_location, place_order)

== User Interaction ==
USER -> AGENT : Prompt\n("Do you have 'Let Us C'?")

== Agent Prompt Processing ==
AGENT -> LLM : Forward Prompt +Tool Catalog
LLM -> LLM : Parse & Analyze\nDetermine relevant tool(s)

== Tool Invocation ==
LLM -> AGENT : Request: Execute Tool\nproduct_info("Let Us C")
AGENT -> AGENT: Verify Too to be invoked is product_info("Let Us C") 

@enduml
